//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryUEF.DBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookStat
    {
        public int Book_ID { get; set; }
        public Nullable<int> BorrowedCount { get; set; }
        public Nullable<int> ReturnedCount { get; set; }
    }
}
