//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryUEF.DBcontext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbBorrowedBook
    {
        public int Borrow_ID { get; set; }
        public int User_ID { get; set; }
        public int Book_ID { get; set; }
        public Nullable<System.DateTime> Borrow_date { get; set; }
        public Nullable<System.DateTime> Return_date { get; set; }
    
        public virtual tbBook tbBook { get; set; }
        public virtual tbUser tbUser { get; set; }
    }
}
